# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to **install** it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
    

## Using NumPy:

In [1]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy . Numpy arrays essentially come in two flavors: **vectors** and **matrices**. Vectors are strictly 1-d arrays and matrices are 2-d .



## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [2]:
#1-D array
my_list = [1,2,3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
#2-D array
two_d_list = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
np.array(two_d_list)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.array(two_d_list).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays


### arange

Return evenly spaced values within a given interval.

In [7]:
np.arange(9).reshape(3,3).shape

(3, 3)

In [8]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

### zeros and ones

Generate arrays of zeros or ones

In [9]:
np.zeros(4)

array([0., 0., 0., 0.])

In [10]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [3]:
np.ones((5,4)) * 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

### linspace
Return evenly spaced numbers over a specified interval. Almost Simmilar to python method range(start,stop,step)

In [13]:
a = range(1,10,2)

In [14]:
list(a)

[1, 3, 5, 7, 9]

In [15]:
#Simmilarly(diff is instead of spet we input number of divisions)

np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

## eye

Creates an identity matrix

In [4]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a **uniform distribution**
over ``[0, 1)``.

In [6]:
from numpy.random import rand

In [7]:
rand(3)

array([0.73835285, 0.45158825, 0.80788919])

In [17]:
np.random.rand(3)

array([0.97037855, 0.52880641, 0.90668091])

In [18]:
np.random.rand(3,2)

array([[0.50245939, 0.09681731],
       [0.28346931, 0.8055992 ],
       [0.49665154, 0.12867572]])

### randn

Return a sample (or samples) from the **"standard normal" distribution**. Unlike rand which is uniform:

In [8]:
np.random.randn(3)

array([ 0.09410223, -0.10147869, -0.76460326])

In [20]:
np.random.randn(3,2)

array([[ 0.00912353, -0.62241023],
       [-0.10274906,  0.6732948 ],
       [-0.12911841, -1.29825993]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [ ]:
np.random.randint()

In [21]:
np.random.randint(1,50)

48

In [10]:
np.random.randint(0,100,10)

array([82, 60, 45, 86, 44, 17, 53, 72, 38, 89])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [11]:
arr = np.arange(25)
rand_arr = np.random.randint(0,50,10)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
rand_arr

array([ 7,  0, 14, 13, 12, 20, 16, 44, 13, 13])

### Reshape
Returns an array containing the same data with a new shape.

In [19]:
arr_2d = arr.reshape(5,5)

In [21]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [14]:
rand_arr

array([ 7,  0, 14, 13, 12, 20, 16, 44, 13, 13])

In [15]:
rand_arr.min()

0

In [16]:
rand_arr.max()

44

In [17]:
#Return indices of the maximum values along the given axis.
rand_arr.argmax()

7

In [31]:
#Return indices of the minimum values along the given axis
rand_arr.argmin()

9

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [22]:
arr_2d.argmax()

24

In [23]:
arr_2d.argmin()

0

### Shape

Shape is an attribute that arrays have (not a method):

In [24]:
arr_2d.shape

(5, 5)

In [34]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)

### dtype

You can also grab the data type of the object in the array:

In [26]:
arr_2d.dtype

dtype('int32')

# Numpy Indexing and Selection

In [27]:
import numpy as np

In [55]:
arr = np.arange(0,11)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[7]

7

In [32]:
arr[2:5]

array([2, 3, 4])

In [33]:
arr[:5]

array([0, 1, 2, 3, 4])

In [34]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [36]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [50]:
arr_2d[2,2].reshape(1,1)

array([[12]])

>>Array and List are almost the same but Array has the ability to **broadcast**

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
arr[0:4] =100

In [60]:
arr1 = arr[0:4]

In [75]:
arr1

100

In [68]:
arr

array([100, 100, 100, 100,   4,   5,   6,   7,   8,   9,  10])

In [69]:
arr_slice = arr[0:5]

In [70]:
arr_slice

array([100, 100, 100, 100,   4])

In [71]:
arr_slice[0:] = 50

In [72]:
arr_slice

array([50, 50, 50, 50, 50])

In [76]:
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

to avoid broadcasting in arrays we use the copy() frunction

In [77]:
arr_copy = arr.copy()

In [78]:
arr_copy

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [79]:
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [80]:
arr_copy[1:4] = 1

In [81]:
arr_copy

array([50,  1,  1,  1, 50,  5,  6,  7,  8,  9, 10])

In [82]:
arr

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

### Indexing 2D array

In [83]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [84]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
arr_2d[0:2,0].reshape(2,1)

array([[1],
       [4]])

In [61]:
#Double bracket notation
arr_2d[1][1]

5

In [62]:
#Single bracket notation
arr_2d[1,2]

6

In [63]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
#Slicing
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [65]:
arr_2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
arr_2d[:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [98]:
# another way of creating 2d array
array_2d = np.arange(50).reshape(5,10)

In [100]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [101]:
array_2d > 25

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [102]:
array_2d[array_2d > 25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49])

In [69]:
array_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [70]:
array_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

### Conditional Selection

In [71]:
arr = np.arange(1,11)

In [72]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [106]:
bool_arr = arr > 5

In [107]:
bool_arr

array([ True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True])

In [108]:
arr[bool_arr]

array([50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

In [109]:
#this can be done in a single step too
arr[arr > 5]

array([50, 50, 50, 50, 50,  6,  7,  8,  9, 10])

# Numpy Operations
    * Array with Array
    * Array with Scalars
    * Universal Array Functions

In [116]:
arr = np.arange(0,11)

In [118]:
arr1 = np.arange(0,12)

In [119]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [121]:
arr + arr1

ValueError: operands could not be broadcast together with shapes (11,) (12,) 

**array with array**

In [111]:
np.nan

nan

In [113]:
arr_add = arr + arr
arr_min = arr - arr
arr_mul = arr * arr

In [114]:
arr_add

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18,  20])

In [81]:
arr_min

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [82]:
arr_mul

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [83]:
# We can also do division - nothing to worry below exception is due to 0/0 .
arr / arr

C:\Users\nayak.AREZZOSKY\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

**Array with Scalar**

In [84]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [85]:
arr + 50

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60])

In [86]:
arr - 10

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [87]:
# this goes on to show how diverse python is as there are multiple ways to obtain same result 
ar = np.arange(-10,1)

In [88]:
ar

array([-10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,   0])

In [89]:
arr * 5

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [90]:
arr / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [91]:
arr // 2

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5], dtype=int32)

In [92]:
arr % 2

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [93]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

**Universal array operations**

Numpy comes with many [universal array functions](https://numpy.org/doc/1.18/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [122]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [123]:
arr.sum()

55

In [124]:
np.sum(arr)

55

In [125]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [126]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [127]:
np.max(arr)

10

In [98]:
np.min(arr)

0

In [128]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [129]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [130]:
np.log(arr)

C:\Users\nayak.AREZZOSKY\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

### Some interesting questions

#### Create an array of 20 linearly spaced points between 0 and 1:

In [113]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [114]:
np.random.randn(25)

array([ 0.14889425, -1.31735569,  1.24452379, -0.0706496 , -0.20966871,
       -0.00655966,  0.82632623, -0.86460624, -0.97239256, -0.88323112,
       -0.15192927,  1.06422038, -0.09718325,  0.57198611, -1.43203144,
       -0.56512109,  0.55009885, -1.16915839,  0.51859822,  0.41821036,
       -0.99017963, -2.16449788, -1.28150075, -0.25286727, -0.04873164])

#### Create an array of the integers from 10 to 50

In [116]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Create an array of all the even integers from 10 to 50

In [117]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [118]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [120]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Thank you