In [2]:
list(range(1,16))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

In [17]:
(15 % 3 == 0 ) & (16 % 5 != 0)

True

In [4]:
15 % 5

0

In [6]:
n = 15

In [18]:
for i in list(range(1, n+1)):
    if (i % 3 == 0) & (i % 5 == 0):
        print('FizzBuzz')
    elif (i % 3 == 0) & (i % 5 != 0):
        print('Fizz')
    elif (i % 5 == 0) & (i % 3 != 0):
        print('Buzz')
    elif (i % 3 != 0) & (i % 5 != 0):
        print(i)

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz


In [27]:
def check(n):
    if (n > 0) & (n < 2*(10**5)):
        print(n)
    else:
        return None
    
check(200000)

In [22]:
2*(10**5)

200000

In [28]:
input()

10


'10'

In [29]:
list(map(int,input().split()))

2 3


[2, 3]

In [30]:
list(input().split())

2 3


['2', '3']

In [31]:
list(map(int,input().split()))

10 5 10


[10, 5, 10]

In [32]:
a,b,c = list(map(int,input().split()))
print(a,b,c)

13 5 2
13 5 2


In [34]:
temp = a
a = b
b = temp 
print(a,b,c)

5 13 2


In [35]:
a,b,c = list(map(int,input().split()))
temp = a
a = b
b = temp
print(a*c,b+c)

13 5 2
10 15


In [39]:
print(ord('F'))

70


In [52]:
ord('*')

42

In [72]:
ord('!')

33

In [73]:
ord('B')

66

In [74]:
ord('c')

99

In [80]:
print(int(ord('F') * (ord('B') / ord('!')) * (ord('c') / ord('!'))))

420


In [81]:
print(ord('Ƥ'))

420


In [82]:
ord('F') * len('abcdef')

420

In [83]:
'ABCD'

['ABCD']

In [85]:
for i in 'ABCD':
    print(i,end='')

ABCD

In [96]:
for i in input():
    if i == 'G':
        i = 'C'
        print(i,end='')
    elif i == 'C':
        i = 'G'
        print(i,end='')
    elif i == 'T':
        i = 'A'
        print(i,end='')
    elif i == 'A':
        i = 'U'
        print(i,end='')
    else:
        print('Invalid Input')

GTAV
CAUInvalid Input


In [95]:
input() in 'ACGT'

GCT


False

In [97]:
d = input()

print(len(d))

ABCG  Z
7


In [102]:
d = input()
r = str()
c = 'A'

for i in range(len(d)):
    if d[i] == 'G':
        r += 'C'
    elif d[i] == 'C':
        r += 'G'
    elif d[i] == 'T':
        r += 'A'
    elif d[i] == 'A':
        r += 'U'
    else:
        c += 'B'

if c == 'A':
    print(r)
else:
    print('Invalid Input')

GCTAAAAAX
Invalid Input


In [103]:
ord('F')

70

In [104]:
ord('P')

80

In [107]:
for i in range(ord('F'),ord('P')+1):
    print(i)

70
71
72
73
74
75
76
77
78
79
80


In [108]:
for i in range(ord('F'),ord('Q')):
    print(i)

70
71
72
73
74
75
76
77
78
79
80


In [115]:
N = input()

# Get the input
numArray = map(int, input().split())

sum_integer = 0
# Write the logic to add these numbers here
numArray = list(numArray)
for i in range(int(N)):
    sum_integer += numArray[i] ** 2



# Print the sum
print(sum_integer)

5
4 7 2 8 5
158


In [114]:
N = input()

# Get the input
numArray = map(int, input().split())

print(N)
print(list(numArray))

5
4 7 2 8 5
5
[4, 7, 2, 8, 5]


In [117]:
L, R = map(int, input().split())

for i in range(L,R+1):
    print(i,end=' ')

5 10
5 6 7 8 9 10 

In [124]:
N = int(input())

# Get the array 
numArray1 = list(map(int, input().split()))
numArray2 = list(map(int, input().split()))

sumArray = []

# Write the logic here:

for i in range(N):
    sumArray.append(numArray1[i] + numArray2[i])

# Print the sumArray
for element in sumArray:
    print(element, end=" ")


3
1 2 3
4 5 6
5 7 9 

In [122]:
l1 = [1,2,3]
l2 = [4,5,6]
sum = []
for i in range(3):
    sum[]

0
1
2


In [125]:
3!

SyntaxError: invalid syntax (<ipython-input-125-a047c859e84d>, line 1)

In [140]:
N = int(input())
fact = 1
for i in range(1,N+1):
    fact *= i
print(fact)

10
3628800


In [139]:
1*2*3*4*5*6*7*8*9*10

3628800

In [141]:
count = [0 for i in range(5 + 1)]
print(count)

[0, 0, 0, 0, 0, 0]


In [19]:
N,m = map(int,input().split())
arr = list(range(N))
l = len(arr)
print(l)
print(arr)

3 1
3
[0, 1, 2]


In [20]:
count = [0 for i in range(N + 1)]  
count[0] = 1

for i in range(1, N + 1): 
    for j in range(l):
        if (i >= arr[j]): 
            count[i] += count[i - arr[j]] 
      
 
print(count[N])

3


In [36]:
import os

In [51]:
def avg(*nums):
    sums = 0.0
    for i in nums:
        sums += i
    l = len(nums)
    a = sums / l
    return a

In [52]:
if __name__ == '__main__':
    #fptr = open(os.environ['OUTPUT_PATH'], 'w')
    
    nums = list(map(int, input().split()))
    res = avg(*nums)
    
    #fptr.write
    print('%.2f' % res + '\n')

    #fptr.close()

5
5.00



In [49]:
class Car:
    def __init__(self,max_speed,speed_unit):
        self.max_speed = max_speed
        self.speed_unit = speed_unit
    
    def __str__(self):
        return 'Car with the maximum speed of '+str(self.max_speed)+' '+str(self.speed_unit)

class Boat:
    def __init__(self,max_speed):
        self.max_speed = max_speed
    
    def __str__(self):
        return 'Boat with the maximum speed of '+str(self.max_speed)+' knots'

In [50]:
if __name__ == '__main__':
    #fptr = open(os.environ['OUTPUT_PATH'], 'w')
    q = int(input())
    queries = []
    for _ in range(q):
        args = input().split()
        vehicle_type, params = args[0], args[1:]
        if vehicle_type == "car":
            max_speed, speed_unit = int(params[0]), params[1]
            vehicle = Car(max_speed, speed_unit)
        elif vehicle_type == "boat":
            max_speed = int(params[0])
            vehicle = Boat(max_speed)
        else:
            raise ValueError("invalid vehicle type")
        #fptr.write
        print("%s\n" % vehicle)
    #fptr.close()

2
car 100 mph
Car with the maximum speed of 100 mph

boat 80
Boat with the maximum speed of 80 knots



In [5]:
n = input()
input_line = input()

input_tup = tuple(map(int,input_line.split()))

print(input_tup)

2
1 2
(1, 2)


In [6]:
print(hash(input_tup))

3713081631934410656


In [9]:
def split_and_join(line):
    a = line.split(' ')
    a = '-'.join(a)
    return a

if __name__ == '__main__':
    line = input()
    result = split_and_join(line)
    print(result)

this is split join
this-is-split-join


In [13]:
a = 'Ross'
b = 'Taylor'
c = a+' '+b
print(c)

Ross Taylor


In [14]:
list(c)

['R', 'o', 's', 's', ' ', 'T', 'a', 'y', 'l', 'o', 'r']

In [20]:
s = 'ABCDCDC'
ss = 'CDC'
for i in range(len(s)):
    if ss in s:
        print(ss)

CDC
CDC
CDC
CDC
CDC
CDC
CDC


In [21]:
def count_substring(string, sub_string):
    return(sum([1 for i in range(0, len(string) - len(sub_string) + 1) if (string[i:(len(sub_string)+i)] == sub_string)]))

In [22]:
count_substring(s,ss)

2

In [23]:
if __name__ == '__main__':
    s = input()



print(any(c.isalnum() for c in s))
print(any(c.isalpha() for c in s))
print(any(c.isdigit() for c in s))
print(any(c.islower() for c in s))
print(any(c.isupper() for c in s))

XA12
True
True
True
False
True


In [37]:
c= 'H'
thickness = 5

In [38]:
for i in range((5+1)//2):
    print((c*25).rjust(30))

     HHHHHHHHHHHHHHHHHHHHHHHHH
     HHHHHHHHHHHHHHHHHHHHHHHHH
     HHHHHHHHHHHHHHHHHHHHHHHHH


In [39]:
for i in range(5):
    print((c*i).rjust(5-1)+c+(c*i).ljust(5-1))

    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH


In [43]:
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             


In [57]:
thickness = int(input()) #This must be an odd number
c = 'H'

#Top Cone
for i in range(thickness):
    print((c*i).rjust(thickness-1)+c+(c*i).ljust(thickness-1))

#Top Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6))

#Middle Belt
for i in range((thickness+1)//2):
    print((c*thickness*5).center(thickness*6))    

#Bottom Pillars
for i in range(thickness+1):
    print((c*thickness).center(thickness*2)+(c*thickness).center(thickness*6)) 

#Bottom Cone
for i in range(thickness):
    print(((c*(thickness-i-1)).rjust(thickness)+c+(c*(thickness-i-1)).ljust(thickness)).rjust(thickness*6))

5
    H    
   HHH   
  HHHHH  
 HHHHHHH 
HHHHHHHHH
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHHHHHHHHHHHHHHHHHHHHHH   
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
  HHHHH               HHHHH             
                    HHHHHHHHH 
                     HHHHHHH  
                      HHHHH   
                       HHH    
                        H     


In [60]:
import textwrap
textwrap.wrap('ABCDEFGHIJKLIMNOQRSTUVWXYZ',4)

['ABCD', 'EFGH', 'IJKL', 'IMNO', 'QRST', 'UVWX', 'YZ']

In [ ]:
def wrap(string, max_width):
    a = textwrap.wrap(string,max_width)
    b = str()
    for i in range(len(a)):
        if i == 0:
            b = b + a[i]
        else:
            b = b +'\n'+a[i]
    return b

In [61]:
n, m = map(int,input().split())
pattern = [('.|.'*(2*i + 1)).center(m, '-') for i in range(n//2)]
print('\n'.join(pattern + ['WELCOME'.center(m, '-')] + pattern[::-1]))

7 21
---------.|.---------
------.|..|..|.------
---.|..|..|..|..|.---
-------WELCOME-------
---.|..|..|..|..|.---
------.|..|..|.------
---------.|.---------


In [64]:
int(10)

10

In [69]:
oct(10)[2:]

'12'

In [75]:
hex(15)[2:].upper()

'F'

In [78]:
bin(17)[2:]

'10001'

In [80]:
len("{0:b}".format(17))

5

In [79]:
'{0:{width}d} {0:{width}o} {0:{width}X} {0:{width}b}'.format(17,width=5)

'   17    21    11 10001'

In [83]:
'{0:5b}'.format(10)

' 1010'

In [84]:
def print_formatted(number):
    pad = len("{0:b}".format(number))
    for i in range(1,number+1):
        print('{0:{width}d} {0:{width}o} {0:{width}X} {0:{width}b}'.format(i,width=pad))


if __name__ == '__main__':
    n = int(input())
    print_formatted(n)

17
    1     1     1     1
    2     2     2    10
    3     3     3    11
    4     4     4   100
    5     5     5   101
    6     6     6   110
    7     7     7   111
    8    10     8  1000
    9    11     9  1001
   10    12     A  1010
   11    13     B  1011
   12    14     C  1100
   13    15     D  1101
   14    16     E  1110
   15    17     F  1111
   16    20    10 10000
   17    21    11 10001


In [86]:
import string
alpha = string.ascii_lowercase

n = int(input())
L = []
for i in range(n):
    s = "-".join(alpha[i:n])
    L.append((s[::-1]+s[1:]).center(4*n-3, "-"))
print('\n'.join(L[:0:-1]+L))

10
------------------j------------------
----------------j-i-j----------------
--------------j-i-h-i-j--------------
------------j-i-h-g-h-i-j------------
----------j-i-h-g-f-g-h-i-j----------
--------j-i-h-g-f-e-f-g-h-i-j--------
------j-i-h-g-f-e-d-e-f-g-h-i-j------
----j-i-h-g-f-e-d-c-d-e-f-g-h-i-j----
--j-i-h-g-f-e-d-c-b-c-d-e-f-g-h-i-j--
j-i-h-g-f-e-d-c-b-a-b-c-d-e-f-g-h-i-j
--j-i-h-g-f-e-d-c-b-c-d-e-f-g-h-i-j--
----j-i-h-g-f-e-d-c-d-e-f-g-h-i-j----
------j-i-h-g-f-e-d-e-f-g-h-i-j------
--------j-i-h-g-f-e-f-g-h-i-j--------
----------j-i-h-g-f-g-h-i-j----------
------------j-i-h-g-h-i-j------------
--------------j-i-h-i-j--------------
----------------j-i-j----------------
------------------j------------------


In [87]:
print(alpha)

abcdefghijklmnopqrstuvwxyz


In [95]:
'-'.join(alpha[0:10])[::-1]

'j-i-h-g-f-e-d-c-b-a'

In [97]:
def print_rangoli(size):
    L = []
    for i in range(n):
        s = "-".join(alpha[i:n])
        L.append((s[::-1]+s[1:]).center(4*n-3, "-"))
    print('\n'.join(L[:0:-1]+L))
    
if __name__ == '__main__':
    n = int(input())
    print_rangoli(n)

10
------------------j------------------
----------------j-i-j----------------
--------------j-i-h-i-j--------------
------------j-i-h-g-h-i-j------------
----------j-i-h-g-f-g-h-i-j----------
--------j-i-h-g-f-e-f-g-h-i-j--------
------j-i-h-g-f-e-d-e-f-g-h-i-j------
----j-i-h-g-f-e-d-c-d-e-f-g-h-i-j----
--j-i-h-g-f-e-d-c-b-c-d-e-f-g-h-i-j--
j-i-h-g-f-e-d-c-b-a-b-c-d-e-f-g-h-i-j
--j-i-h-g-f-e-d-c-b-c-d-e-f-g-h-i-j--
----j-i-h-g-f-e-d-c-d-e-f-g-h-i-j----
------j-i-h-g-f-e-d-e-f-g-h-i-j------
--------j-i-h-g-f-e-f-g-h-i-j--------
----------j-i-h-g-f-g-h-i-j----------
------------j-i-h-g-h-i-j------------
--------------j-i-h-i-j--------------
----------------j-i-j----------------
------------------j------------------


In [111]:
a = 'hello world'.split()
b = ''

In [112]:
for i in range(len(a)):
    if i == 0:
        b = a[i].capitalize()
    else:
        b = b +' '+ a[i].capitalize()
print(b)

Hello World


In [115]:
len(set(['UK','USA','FRA','IND','UK','BRA']))

5

In [116]:
a = set([])

In [118]:
a.add('UK')

In [119]:
a

{'UK'}

In [126]:
name = set()
#if __name__ == '__main__':
for _ in range(int(input())):
    name.add(input())

3
a
a
b


In [127]:
print(name)

{'a', 'b'}


In [128]:
print(len(name))

2


In [130]:
n = int(input())
s = set(map(int, input().split()))

2
3 5


In [131]:
print(sum(s))

8


In [133]:
n = int(input())
s = set(map(int, input().split()))
l = []

for _ in range(int(input())):
    l.append(input())


for i in range(len(l)):
    if l[i].split()[0] == 'pop':
        s.pop()
    if l[i].split()[0] == 'remove':
        s.remove(int(l[i].split()[1]))
    if l[i].split()[0] == 'discard':
        s.discard(int(l[i].split()[1])) 

print(sum(s))

5
1 2 3 4 5
2
pop
discard 2
12


In [8]:
n = int(input())
col = list(input().split())
l = [x for x in range(len(col)) if col[x]=='MARKS']
for i in range(n):
    l.append(int(input().split()[l[0]]))

print('{0:.2f}'.format(sum(l[1:]) / len(l[1:])))

2
MARKS ID
20 1
30 2
25.00


In [6]:
int(input().split()[1])

20

In [9]:
from collections import OrderedDict

In [10]:
ordinary_dictionary = {}

In [11]:
ordinary_dictionary['a'] = 1
ordinary_dictionary['b'] = 2
ordinary_dictionary['c'] = 3
ordinary_dictionary['d'] = 4
ordinary_dictionary['e'] = 5

In [12]:
print(ordinary_dictionary)

{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}


In [21]:
ordinary_dictionary.items()

dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)])

In [13]:
z = OrderedDict([('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5)])

1

In [16]:
d = OrderedDict()
for _ in range(int(input())):
    item, space, quantity = input().rpartition(' ')
    d[item] = d.get(item, 0) + int(quantity)
for item, quantity in d.items():
    print(item, quantity)

2
a 12
a 10
a 22


In [22]:
from collections import Counter, OrderedDict
class OrderedCounter(Counter, OrderedDict):
    pass
d = OrderedCounter(input() for _ in range(int(input())))
print(len(d))
print(*d.values())

4
abcd
abcdef
acd
abcdefgh
4
1 1 1 1


In [ ]:
import collections

numShoes = int(input())
shoes = collections.Counter(map(int, input().split()))
numCust = int(input())

income = 0

for i in range(numCust):
    size, price = map(int, input().split())
    if shoes[size]: 
        income += price
        shoes[size] -= 1

print(income)

In [27]:
for i in range(1,int(input())):
    print([0,1,22,333,4444,55555,666666,7777777,88888888,999999999][i])

3
1
22


In [25]:
for i in range(1,int(input())):
    print(i)

5
1
2
3
4


In [26]:
for i in range(1,5):
    print(i)

1
2
3
4


In [1]:
for i in range(1,10):
    print((10**(i)//9)*i)

1
22
333
4444
55555
666666
7777777
88888888
999999999


___


___


# Numpy

___


___

In [2]:
import numpy as np

def arrays(arr):
    return np.array(arr,float)[::-1]


arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3
[3. 2. 1.]


In [4]:
arr = input().strip().split(' ')

arr = np.array(arr,int)

print(np.reshape(arr,(3,3)))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
arr = list(map(int,input().strip().split(' ')))
arr

1 2 3


[1, 2, 3]

In [12]:
nm = list(map(int,input().strip().split(' ')))
l= []
for i in range(nm[0]):
    l1 = list(map(int,input().strip().split(' ')))
    l.append(l1)


arr = np.array(l)

print(np.transpose(arr))
print(arr.flatten())

3 2
1 2
3 4
5 6
[[1 3 5]
 [2 4 6]]
[1 2 3 4 5 6]


In [20]:
a1 = np.array([[1,2,3],[1,2,3]])
a2 = np.array([[4,5,6],[4,5,6]])
np.concatenate((a1,a2),axis=1)

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 4, 5, 6]])

In [22]:
nmp = list(map(int,input().strip().split(' ')))
np_l=[]
mp_l=[]

for i in range(nmp[0]):
    l1 = list(map(int,input().strip().split(' ')))
    np_l.append(l1)

for i in range(nmp[1]):
    l2 = list(map(int,input().strip().split(' ')))
    mp_l.append(l2)    

arr_np = np.array(np_l)
arr_mp = np.array(mp_l)

print(np.concatenate((arr_np,arr_mp),axis = 0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [24]:
np.zeros((3,3),int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [32]:
abc = list(map(int,input().strip().split(' ')))

print (np.zeros(abc,int))
print (np.ones(abc,int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [43]:
print(str(np.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [45]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [47]:
np.true_divide(a,b)

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

In [ ]:
nm = list(map(int,input().strip().split(' ')))
a = []
for i in range(nm[0]):
        a.append(list(map(int,input().strip().split(' '))))
print(a)

In [4]:
def unique(list1): 
  
    # intilize a null list 
    unique_list = [] 
      
    # traverse for all elements 
    for x in list1: 
        # check if exists in unique_list or not 
        if x not in unique_list: 
            unique_list.append(x) 
    
    print(unique_list)


In [5]:
unique([1,1,1,2,3,4,2,3,5,5])

[1, 2, 3, 4, 5]


In [ ]:
def sockMerchant(n, ar):
    unique_ar = []
    for x in ar:
        if x not in unique_ar:
            unique_ar.append(x)
    
    for i in range(len(unique_ar)):
        for j in range(len(ar)):
            if unique_ar[i] == ar[j]
            cnt += 1

In [10]:
ar = list(map(int,'10 20 20 10 10 30 50 10 20'.split()))

In [17]:
ar

[10, 20, 20, 10, 10, 30, 50, 10, 20]

In [14]:
unique_ar=[]
for x in ar:
    if x not in unique_ar:
        unique_ar.append(x)
        
unique_ar

[10, 20, 30, 50]

In [22]:
pair=[]
for i in range(len(unique_ar)):
    cnt = 0
    for j in range(len(ar)):
        if unique_ar[i] == ar[j]:
            cnt += 1
    pair.append(cnt//2)

In [23]:
pair

[2, 1, 0, 0]

In [24]:
sum(pair)

3

In [28]:
s='ABCD'

In [30]:
len(s)

4

In [31]:
path = 'UDDDUDUU'

In [33]:
sl = 0
v_cnt = 0

In [35]:
for i in range(len(path)):
    print(path[i])

U
D
D
D
U
D
U
U


In [37]:
for i in range(len(path)):
    if path[i] == 'U':
        sl += 1
        if sl == 0:
            v_cnt += 1
    else:
        sl -= 1      

In [38]:
v_cnt

1

In [87]:
b = list(map(int,'0 0 1 0 0 1 0'.split()))

In [88]:
b

[0, 0, 1, 0, 0, 1, 0]

In [89]:
jump = 0
ic = 0

In [93]:
def jumpingOnClouds(b):
    jump = 0
    ic = 0
    for i in range(len(b)):
        if ic < len(b)-2:
            if i == ic:
                if (b[i+1]==0) & (b[i+2]==0):
                    jump += 1
                    ic += 2
                elif (b[i+1]==0) & (b[i+2]==1):
                    jump +=1
                    ic += 1
                elif (b[i+1]==1) & (b[i+2]==0):
                    jump +=1
                    ic += 2
            else:
                jump = jump
        elif ic == len(b)-2:
            if i == ic:
                if b[i+1] == 0:
                    jump +=1
                    ic +=1
    return jump

In [94]:
jumpingOnClouds(b)

4

In [129]:
a = 'aba'
n = 10

In [106]:
for i in range(n):
    a='aba'
    a = a+a

In [130]:
a

'aba'

In [131]:
a = a*n

In [132]:
a[:n]

'abaabaabaa'

In [134]:
s, n = input().strip(), int(input().strip())
print(s.count("a") * (n // len(s)) + s[:n % len(s)].count("a"))

aba
10
7


In [135]:
s

'aba'

In [137]:
n

10

In [138]:
s[:n % len(s)].count("a")

1

In [8]:
result = 1,1

In [9]:
print(' '.join(map(str, result)))

1 1


In [12]:
sum_l = [1000000001,1000000002,1000000003,1000000004,1000000005]

In [15]:
sum_l

[1000000001, 1000000002, 1000000003, 1000000004, 1000000005]

In [16]:
su = 0
for i in range(len(sum_l)):
    su += sum_l[i]
su

5000000015

In [17]:
arr = []
for _ in range(3):
    arr.append(list(map(int, input().rstrip().split())))


1 2 3
1 2 3
1 2 3


In [18]:
arr

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [21]:
arr[0][0]

1

In [22]:
arr[1][1]

2

In [23]:
arr[2][2]

3

In [24]:
arr[0][-1]

3

In [26]:
arr[1][-2]

2

In [27]:
arr[2][-3]

1

In [28]:
abs(-9)

9

In [29]:
def diagonalDifference(arr):
    # Write your code here
    pd = 0
    sd = 0
    for i in range(n):
        pd += arr[i][i]
        sd += arr[i][-(i+1)]
    return abs(pd-sd)


if __name__ == '__main__':
    

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    print(result)

3
4 5 6
7 8 9
1 2 3
0


In [3]:
'#'*0.rjust(4)

SyntaxError: invalid syntax (<ipython-input-3-897b3bc961b2>, line 1)

In [4]:
h = '#'

In [8]:
(h*1).rjust(4)

'   #'

In [9]:
(h*2).rjust(4)

'  ##'

In [10]:
(h*3).rjust(4)

' ###'

In [11]:
(h*4).rjust(4)

'####'

In [22]:
n = int(input())
h= '#'
for i in range(n):
    print((h*(i+1)).rjust(n))

5
    #
   ##
  ###
 ####
#####


In [27]:
l = [5,4,3,2,1]

In [28]:
l.sort()

In [29]:
l

[1, 2, 3, 4, 5]

In [30]:
l_min = l[:n-1]
l_min

[1, 2, 3, 4]

In [31]:
l_max = l[1:]
l_max

[2, 3, 4, 5]

In [32]:
sum(l_min)

10

In [33]:
sum(l_max)

14

In [34]:
max(l)

5

In [64]:
t = '07:05:45PM'

In [55]:
t = t.split(':')
t

['07', '05', '45PM']

In [56]:
if t[2][2:] == 'PM':
    t[0] = int(t[0]) +12
    t[0] = str(t[0])

In [57]:
t

['19', '05', '45PM']

In [65]:
t = t.split(':')
if t[2][2:] == 'PM':
    t[0] = int(t[0]) +12
    t[0] = str(t[0])
nt=''
for i in range(len(t)):
    if i ==0:
        nt += t[i]
    else:
        nt += ':'+t[i]
print(nt[:len(nt)-2])

19:05:45


In [66]:
def timeConversion(s):
    s = s.split(':')
    if s[2][2:] == 'PM':
        if s[0] != '12':
            s[0] = int(s[0]) +12
            s[0] = str(s[0])
    else:
        if s[0] == '12':
            s[0] = '00'
    nt=''
    for i in range(len(s)):
        if i ==0:
            nt += s[i]
        else:
            nt += ':' + s[i]
    return (nt[:len(nt)-2])


if __name__ == '__main__':
    s = str(input())
    result = timeConversion(s)
    print(result)

07:05:45PM
19:05:45


In [67]:
n = int(input())
missiles = []
for _ in range(n):
    missiles.append(list(map(int, input().rstrip().split())))

4
1 1
2 3
3 1
5 1


In [68]:
missiles

[[1, 1], [2, 3], [3, 1], [5, 1]]